name: DotnetEventBus

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:3-management-alpine
        ports: 
        - 15672:15672
        - 5672:5672
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup dotnet core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
           5.0.x
           6.0.x
           3.1.x
      - run: dotnet build
      - run: dotnet test
          